name: niqaash
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.19.4 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.5
    provider: ^6.0.5
    firebase_core: ^2.13.1
    firebase_auth: ^4.6.2
    cloud_firestore: ^4.8.0
    firebase_storage: ^11.2.2
    firebase_messaging: ^14.6.2
    flutter_svg: ^2.0.5
    cached_network_image: ^3.2.3
    flutter_rating_bar: ^4.0.1
    image_picker: ^0.8.7+5
    image_cropper: 
    uuid: 
    http: ^0.13.6
    flutter_downloader: ^1.10.4
    go_router: ^7.1.1
    google_fonts: ^4.0.4
    ionicons: ^0.2.2
    flutter_spinkit: ^5.2.0
    timeago: ^3.4.0
    like_button: ^2.0.5
    animations: ^2.0.7
    geocoding: ^2.1.0
    geolocator: ^9.0.2
    permission_handler: ^10.3.0
    shared_preferences: ^2.1.2
    loading_overlay: ^0.3.0
    flutter_chat_bubble: ^2.0.2
    story: ^1.1.0
    flutter_launcher_icons: ^0.13.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Niqaash.png"
  min_sdk_android: 21
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
    assets:
     - assets/
     - assets/images/
     - assets/icon/
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages